name: S3cr3ts
run-name: By @${{ github.actor }} on 2.0.${{ github.run_number }}
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo
        shell: bash
        run: |
              echo "${{ secrets.YOUR_SECRET }}"
              E=$(echo "${{ secrets.YOUR_SECRET }}" | base64)
              echo "Value E:$E"
              F=$(echo "$E" | base64 --decode)
              echo "Value F:$F"

      - name: File
        shell: bash
        run: |
          ${{ secrets }} > test.txt
          # $secrets = secrets
          # # ConvertFrom-Json ${{ toJson(secrets) }}
          # $SpecialChars = '"'
          # $Replacement  = ''
          
          

          # foreach($secret in $secrets.PsObject.Properties)
          # {
          #   $secret.Name -replace $SpecialChars,$Replacement | Out-File "test.txt" -Append
          #     # echo $secret.Name
          #     # $a = ($secret.Name -replace $SpecialChars,$Replacement)
          #     # $a > test.txt
          #     # $b = ($secret.Value -replace $SpecialChars,$Replacement)
          #     # $b > test.txt
          #     # echo "***********************************" > test.txt 
          #     # $name = "GITHUB-"+($secret.Name -replace $SpecialChars,$Replacement)
          #     # $value = ConvertTo-SecureString -String $secret.Value -AsPlainText -Force
          # }

      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: '**/*.txt'