name: sha
run-name: 'By @${{ github.actor }} on ${{ github.run_number }} event ${{ github.event_name }} github_sha=${{ github.sha }}'
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SHA PR
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
            echo "GITHUB_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - name: SHA PUSH
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
            echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: echo
        shell: bash
        run: |
              echo "github_sha=${{ github.sha }}"
              echo "github_event_pull_request_head_sha=${{ github.event.pull_request.head.sha }}"
              echo "github_event_pull_request_base_sha=${{ github.event.pull_request.base.sha}}"
              echo "GITHUB_ENV=${{ env.GITHUB_SHA }}"