name: Test
run-name: Deploy Shared Build by @${{ github.actor }} on 2.0.${{ github.run_number }}
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read
  deployments: read
  id-token: none
  issues: read
  discussions: none
  packages: write
  pages: none
  pull-requests: write
  repository-projects: read
  security-events: none
  statuses: read

env: 
    workingDirectory: './shared/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ls
        shell: bash
        run: |
              ls -a

      # - name: Install git
      #   run: sudo apt-get install -y git

      - name: list
        shell: bash
        run: |
              echo "git diff --name-only $(git rev-parse --short origin/main)...github.event.pull_request.head.sha"
              git diff --name-only $(git rev-parse --short origin/main)...${{ github.event.pull_request.head.sha }}

              echo "git diff --name-only  $(git rev-parse --short origin/main)...HEAD"
              git diff --name-only $(git rev-parse --short origin/main)...HEAD

              echo "git diff --name-only  github.sha ...github.event.pull_request.head.sha"
              echo "github.sha=${{github.sha}} github.event.pull_request.head.sha=${{github.event.pull_request.head.sha}}"
              git diff --name-only ${{ github.sha }}...${{ github.event.pull_request.head.sha }}

              echo "git --no-pager diff --name-only --diff-filter=ACMRT github.event.pull_request.base.sha github.sha"
              echo "github.event.pull_request.base.sha=${{ github.event.pull_request.base.sha }} github.sha=${{github.sha}}"
              git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{github.sha}}

              echo "git diff --stat --name-only $COMMIT^ $COMMIT   | xargs git ls-tree --full-tree  $COMMIT| awk '{print $4}'"
              echo "COMMIT=${{ github.sha }}"
              COMMIT=${{ github.sha }}
              git diff --stat --name-only $COMMIT^ $COMMIT   | xargs git ls-tree --full-tree  $COMMIT| awk '{print $4}'

              echo "sha HEAD"
              git rev-parse --short HEAD

              echo "sha main"
              git rev-parse --short origin/main
                
# | cut -f1-3 -d"/" | grep "${{ inputs.workingDirectory}}" | grep -Ev "^*[Tt]est" | sort | uniq ) -type f \( -iname "*.csproj" ! -iname "*Tests*.csproj" \) -print0 | xargs -0 -t -P 10 -I{} sh -c 'file=$1; dotnet pack "$file" --configuration ${{ inputs.buildConfiguration }} -p:PackageVersion=${{ env.BUILD_VERSION }} --no-build --output . ;' xargs-sh {}
# --name-only main...HEAD
